### ISSUE TITLE
Latest release on pypi is 1.3.5, of which setup.py declares version 1.3.4

### ISSUE THREAD

**Issue by tshirtman** [jiangwen365/pypyodbc#107]
This is broken in pip>=20.3.

Considering the ageing release, it seems like it would make a new release a good idea :).

**Comment by ethanjosephscott** [comment]
I haven't tested it out however in the setup.py file lists under "version" '1.3.4' when it should be '1.3.5'.  in master this field looks like this 'version=pypyodbc.version'.  With the repository founder seemingly awol are we capable of doing a release?

**Comment by braian87b** [comment]
Hi !

https://github.com/jiangwen365/pypyodbc/issues/79#issuecomment-573166003

**Comment by braian87b** [comment]
https://github.com/jiangwen365/pypyodbc/issues/89
https://github.com/jiangwen365/pypyodbc/issues/88#issuecomment-429326231
https://github.com/jiangwen365/pypyodbc/issues/82#issuecomment-393569843

**Comment by ethanjosephscott** [comment]
Hey @braian87b If you would give me the necessary access, I would take the time and effort to get this straightened out

**Comment by braian87b** [comment]
We should get in touch with @jiangwen365 since I just checked and currently I do not have permissions on the repo to add new collaborators.

**Comment by ethanjosephscott** [comment]
@braian87b Okay i just sent him an email on a different but actively maintained project of his, because we would need a Chinese national to signup for said social media website.

**Comment by rolweber** [comment]
Two months since the last comment - I suppose no response from the project creator.
If there's serious interest in getting a new release out, it may be necessary to fork this repo.

I could write up the steps for you, @braian87b. Should take an hour or less, depending on how good you are with writing. Afterwards, you'd be the administrator of the forked repo and could grant people access.

But after a fork and new release, the lengthy process to [get access to the abandoned PyPI project](https://www.python.org/dev/peps/pep-0541/#how-to-request-a-name-transfer) is waiting for any volunteers.

**Comment by braian87b** [comment]
@rolweber Hey, Let me know what should I do.

**Comment by rolweber** [comment]
1. [Create a new organization](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch) "pypyodbc" on GitHub.
   - Pick a name for the new repo in that organization. I suggest "pypyodbc", so the new repo will become available at  \
      https://github.com/pypyodbc/pypyodbc/
2. Prepare the current repo for the fork. Put in links to the new repo, although that doesn't exist yet. This is important to establish authenticity of the new repo.
   - Add a section to the top of README.md, explaining that development moves to the new repo.  Where it currently says "This is the GitHub homepage of pypyodbc".  \
     Phrase the explanation in a way that will also work when it appears in the new repo :-)
   - [Create an issue template](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) that says "Development has moved. Please open new issues at _newrepo_/issues".
    - [Create a PR template](https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository) that says "Development has moved. Please open PRs for _newrepo_ instead."
    - Once you're satisified with the README and templates, create a tag "move-to-pypyodbc-org" or similar, to mark the point of departure.
3. Create a copy of this repo in the new org, with the name chosen above. There are different ways to copy the repo. Either way, the issues and pending PRs will remain here. The Wiki needs to be copied separately.
   - Use the [GitHub importer](https://docs.github.com/en/github/importing-your-projects-to-github/importing-a-repository-with-github-importer) in the new org to import this repo.
   - Alternatively, fork this repo into the new org. Then contact GitHub support to detach the fork from its upstream. Otherwise, PRs in the fork would be opened against upstream by default, which is terribly annoying.
   - Alternatively, clone this repo to your workstation. Create a new, empty repo in the new org. Really empty, not even a read me.  In the clone on your workstation, configure the new repo as an upstream. Push your clone to the new repo.
4. Clean up the new repo:
    - Go to Settings and enable Issues. (Depending on how you created the copy, this might already be enabled.)
    - Edit README.md, explaining that this is the new home of pypyodbc. Provide a back link to the former repo.
    - Remove the issue template and PR template.
5. Optionally, can be done later: [Copy the wiki](https://stackoverflow.com/a/56480628/5629418) from this repo to the new one.
6. If possible, make @jiangwen365 an editor of the new org or repo. They probably don't care, but it's a matter of courtesy and recognition. I'm not sure though if you can grant someone access without them accepting it.

I hope I didn't miss anything of importance :-)

**Comment by braian87b** [comment]
Alright, :rocket: 

It's live here: https://github.com/pypyodbc/pypyodbc

- I skipped the tag "move-to-pypyodbc-org" part (was it necessary?)
- I used the GitHub importer
- Issues seems to be already enabled
- Didn't copied the wiki, can you please try to do that step?
- I invited @jiangwen365 but the invite is pending to be accepted

**Comment by braian87b** [comment]
@rolweber let me know further steps, will be attentive.

**Comment by rolweber** [comment]
If nothing gets merged in the old repo anymore, creating a tag is not required. The idea was that anyone who cares can easily find out at which point the fork took place.

**Comment by rolweber** [comment]
~You can remove the stale branches from the new repo :-)~

Actually, I could do that as well :-) Thanks for the invitation.

**Comment by rolweber** [comment]
I tagged the last common commit in the new repo:
https://github.com/pypyodbc/pypyodbc/releases/tag/point-of-departure

**Comment by rolweber** [comment]
Don't know yet when I will find time to look into the Wiki migration. But I guess there's no hurry.

**Comment by rolweber** [comment]
I copied the wiki. And I figured out which commit was last released to PyPI. That is now tagged as a version:
https://github.com/pypyodbc/pypyodbc/releases/tag/v1.3.5

How do you feel about renaming the master branch to main? Some people are offended by the term.

**Comment by braian87b** [comment]
done.

**Comment by sodul** [comment]
@rolweber @braian87b are you in the process of claiming ownership of pypyodbc on PyPI? We have pinned our own `requirements.txt` to `pypyodbc==1.3.2` to avoid pip complaints, so there is no rush to get the ball moving.

**Comment by rolweber** [comment]
I'm not. Neither am I planning to.

Maybe some volunteer steps up to handle the administrative stuff? Search for historical records about failed attempts to reach @jiangwen365, make some new attempts, tell the PyPI admins about it, try again after some weeks,...

I have neither the patience nor the motivation required for that.

**Comment by rolweber** [comment]
@braian87b Do you have an account on PyPI? Assuming that a volunteer steps up, it would make sense to transfer ownership of the PyPI project to you. You're the only person around who has write access to the original repo. I think that will go a long way to convince the PyPI admins that the project would be safe with you.

**Comment by nickolay** [comment]
> @braian87b Do you have an account on PyPI? Assuming that a volunteer steps up, it would make sense to transfer ownership of the PyPI project to you. You're the only person around who has write access to the original repo. I think that will go a long way to convince the PyPI admins that the project would be safe with you.

I fired an email to @jiangwen365 (the only e-mail I found was the one listed on the [pypi page](https://pypi.org/project/pypyodbc/)) asking them to look into this, though [previous attempts apparently didn't have any result](https://github.com/jiangwen365/pypyodbc/issues/107#issuecomment-779649372).

The [PEP-541 process](https://www.python.org/dev/peps/pep-0541/#how-to-request-a-name-transfer) requires [filling in a form](https://github.com/pypa/pypi-support/issues/new?labels=PEP+541&template=pep541-request.yml&title=PEP+541+Request%3A+PROJECT_NAME) with the PyPI username of the new maintainer, so unless @braian87b or someone else steps up and shares their pypi username, no volunteer can help with the name transfer..

**Comment by braian87b** [comment]
Let me take a look, right now.

**Comment by braian87b** [comment]
Alright, I just set up the request here: https://github.com/pypa/pypi-support/issues/1133

**Comment by sodul** [comment]
The transfer completed!

**Comment by sodul** [comment]
@braian87b you are the owner now, will you release 1.3.6 to fix the versioning issue?

**Comment by nickolay** [comment]
I tried looking into what needs to happen for a 1.3.6 release.

First during my attempt to locate sources for the latest (2017-01-30) release on PyPI, I noticed that https://github.com/pypyodbc/pypyodbc/releases/tag/v1.3.5 points to a wrong commit. The correct one is https://github.com/jiangwen365/pypyodbc/commit/044227a7c67e5322f4ec4368c92680d9a696bc44, but it [doesn't exactly match what's on PyPI either](https://github.com/nickolay/pypyodbc/commit/fc2c9a4e8fc6ef6b29bb82951564c96657572e81) (in its setup.py / PKG-INFO metadata)

I tried bringing setup.py closer to what's on currently on PyPI in https://github.com/nickolay/pypyodbc/commit/568071444cf0dc442801749797faec2da7815952#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7

I believe the least invasive way to release 1.3.6 (with only a fix to the versioning problem, and without any other breaking changes such as https://github.com/pypyodbc/pypyodbc/issues/5) is to build the source distribution (`python setup.py sdist`) from https://github.com/nickolay/pypyodbc/tree/568071444cf0dc442801749797faec2da7815952 and then follow the instructions at https://packaging.python.org/tutorials/packaging-projects/#uploading-the-distribution-archives to publish to (Test)PyPI. Can anyone double-check?

@braian87b can you make a test pypi release, please?

**Comment by rolweber** [comment]
Thanks for spotting the problems with the commit I tagged as suspect for 1.3.5.2. I've linked your comment in the release description now. I'll try to free up a few hours later this month for working towards a re-release. The project isn't on test.pypi yet, so that's something I might be able to do.

**Comment by rolweber** [comment]
[Release 1.3.6](https://github.com/pypyodbc/pypyodbc/releases/tag/v1.3.6) from [pypyodbc/pypyodbc](https://github.com/pypyodbc/pypyodbc/) is published on PyPI now: https://pypi.org/project/pypyodbc/1.3.6/

@tshirtman or @braian87b, could you please close this issue? I don't have the permission to do that.

**Comment by tshirtman** [comment]
Done! Thanks for the work to take over and fix this.
